include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    non_part_of_directive_in_part: ignore
  enable-experiment:
    - macros