name: flutter_supabase_macro
description: "A new Flutter project."
version: 0.0.6
homepage:

environment:
  sdk: ^3.6.0-216.1.beta
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.2-main.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

